// Auto-generated migration scope data (from catalog analysis).
const reportData = {
  meta: {
    source: 'https://wknd.site/us/en.html',
    date: '2026-07-22',
    method: 'crawl',
  },
  metrics: {
    totalPages: 64,
    totalTemplates: 6,
    analyzedTemplates: 6,
    totalBlockTypes: 31,
    edsBlockVariants: 24,
    unknownBlockVariants: 7,
    localeCount: 7,
    percentAnalyzed: 100,
    pagesAnalyzed: 64,
    pagesFailed: 0,
  },
  locales: [
    {
      locale: 'us',
      pages: 27,
    },
    {
      locale: 'ca',
      pages: 30,
    },
    {
      locale: 'ch',
      pages: 3,
    },
    {
      locale: 'de',
      pages: 1,
    },
    {
      locale: 'fr',
      pages: 1,
    },
    {
      locale: 'es',
      pages: 1,
    },
    {
      locale: 'it',
      pages: 1,
    },
  ],
  templates: [
    {
      name: 'adventure-detail',
      count: 32,
      desc: 'Adventure detail page: breadcrumb, full-width hero carousel, two-column layout with a metadata sidebar and tabbed rich-text content with inline image',
      rep: 'https://wknd.site/ca/en/adventures/bali-surf-camp.html',
      urls: [
        'https://wknd.site/ca/en/adventures/bali-surf-camp.html',
        'https://wknd.site/ca/en/adventures/beervana-portland.html',
        'https://wknd.site/ca/en/adventures/climbing-new-zealand.html',
        'https://wknd.site/ca/en/adventures/colorado-rock-climbing.html',
        'https://wknd.site/ca/en/adventures/cycling-southern-utah.html',
        'https://wknd.site/ca/en/adventures/cycling-tuscany.html',
        'https://wknd.site/ca/en/adventures/downhill-skiing-wyoming.html',
        'https://wknd.site/ca/en/adventures/gastronomic-marais-tour.html',
        'https://wknd.site/ca/en/adventures/napa-wine-tasting.html',
        'https://wknd.site/ca/en/adventures/riverside-camping-australia.html',
        'https://wknd.site/ca/en/adventures/ski-touring-mont-blanc.html',
        'https://wknd.site/ca/en/adventures/surf-camp-costa-rica.html',
        'https://wknd.site/ca/en/adventures/tahoe-skiing.html',
        'https://wknd.site/ca/en/adventures/west-coast-cycling.html',
        'https://wknd.site/ca/en/adventures/whistler-mountain-biking.html',
        'https://wknd.site/ca/en/adventures/yosemite-backpacking.html',
        'https://wknd.site/us/en/adventures/bali-surf-camp.html',
        'https://wknd.site/us/en/adventures/beervana-portland.html',
        'https://wknd.site/us/en/adventures/climbing-new-zealand.html',
        'https://wknd.site/us/en/adventures/colorado-rock-climbing.html',
        'https://wknd.site/us/en/adventures/cycling-southern-utah.html',
        'https://wknd.site/us/en/adventures/cycling-tuscany.html',
        'https://wknd.site/us/en/adventures/downhill-skiing-wyoming.html',
        'https://wknd.site/us/en/adventures/gastronomic-marais-tour.html',
        'https://wknd.site/us/en/adventures/napa-wine-tasting.html',
        'https://wknd.site/us/en/adventures/riverside-camping-australia.html',
        'https://wknd.site/us/en/adventures/ski-touring-mont-blanc.html',
        'https://wknd.site/us/en/adventures/surf-camp-costa-rica.html',
        'https://wknd.site/us/en/adventures/tahoe-skiing.html',
        'https://wknd.site/us/en/adventures/west-coast-cycling.html',
        'https://wknd.site/us/en/adventures/whistler-mountain-biking.html',
        'https://wknd.site/us/en/adventures/yosemite-backpacking.html',
      ],
      analyzed: true,
      blocks: [
        'breadcrumbs-minimal-dark',
        'carousel-minimal-dark',
        'metadata-minimal-dark',
        'tabs-minimal-dark',
      ],
    },
    {
      name: 'article',
      count: 12,
      desc: 'Magazine article page: full-width hero image, breadcrumb, article title and byline, rich-text body with section headings and inline images, a share sidebar with related-story links, and author footer',
      rep: 'https://wknd.site/ca/en/magazine/arctic-surfing.html',
      urls: [
        'https://wknd.site/ca/en/magazine/arctic-surfing.html',
        'https://wknd.site/ca/en/magazine/guide-la-skateparks.html',
        'https://wknd.site/ca/en/magazine/members-only/alaskan-adventure.html',
        'https://wknd.site/ca/en/magazine/members-only/fly-fishing-the-amazon.html',
        'https://wknd.site/ca/en/magazine/san-diego-surf.html',
        'https://wknd.site/ca/en/magazine/ski-touring.html',
        'https://wknd.site/ca/en/magazine/western-australia.html',
        'https://wknd.site/us/en/magazine/arctic-surfing.html',
        'https://wknd.site/us/en/magazine/guide-la-skateparks.html',
        'https://wknd.site/us/en/magazine/san-diego-surf.html',
        'https://wknd.site/us/en/magazine/ski-touring.html',
        'https://wknd.site/us/en/magazine/western-australia.html',
      ],
      analyzed: true,
      blocks: [
        'breadcrumbs-minimal-dark',
        'quote-minimal-dark',
        'cards-share-minimal-dark',
      ],
    },
    {
      name: 'homepage',
      count: 11,
      desc: 'Locale landing page: full-width hero carousel, featured article split layout, recent articles card row, secondary hero, and a destination card grid',
      rep: 'https://wknd.site/ca/en.html',
      urls: [
        'https://wknd.site/ca/en.html',
        'https://wknd.site/ca/fr.html',
        'https://wknd.site/ch/de.html',
        'https://wknd.site/ch/fr.html',
        'https://wknd.site/ch/it.html',
        'https://wknd.site/de/de.html',
        'https://wknd.site/es/es.html',
        'https://wknd.site/fr/fr.html',
        'https://wknd.site/it/it.html',
        'https://wknd.site/us/en.html',
        'https://wknd.site/us/es.html',
      ],
      analyzed: true,
      blocks: [
        'carousel-minimal-dark',
        'hero-minimal-dark',
        'cards-minimal-dark',
      ],
    },
    {
      name: 'content-listing',
      count: 5,
      desc: 'Editorial listing page with a section title, intro text, and repeated rows of circular/portrait cards with names and social links (about-us and magazine landing)',
      rep: 'https://wknd.site/ca/en/about-us.html',
      urls: [
        'https://wknd.site/ca/en/about-us.html',
        'https://wknd.site/ca/en/magazine.html',
        'https://wknd.site/ca/en/magazine/members-only.html',
        'https://wknd.site/us/en/about-us.html',
        'https://wknd.site/us/en/magazine.html',
      ],
      analyzed: true,
      blocks: [
        'cards-profile-minimal-dark',
      ],
    },
    {
      name: 'adventures-listing',
      count: 2,
      desc: 'Adventures listing page: full-width hero with overlay intro card and a filterable grid of adventure teaser cards',
      rep: 'https://wknd.site/ca/en/adventures.html',
      urls: [
        'https://wknd.site/ca/en/adventures.html',
        'https://wknd.site/us/en/adventures.html',
      ],
      analyzed: true,
      blocks: [
        'hero-minimal-dark',
        'tabs-minimal-dark',
        'cards-minimal-dark',
      ],
    },
    {
      name: 'faq',
      count: 2,
      desc: 'FAQ page: title, hero image, intro paragraph, accordion of question/answer items, and a right-hand contact sidebar',
      rep: 'https://wknd.site/ca/en/faqs.html',
      urls: [
        'https://wknd.site/ca/en/faqs.html',
        'https://wknd.site/us/en/faqs.html',
      ],
      analyzed: true,
      blocks: [
        'accordion-minimal-dark',
      ],
    },
  ],
  blocks: [
    {
      id: 'footer-global',
      base: 'footer',
      desc: 'Block variant: footer',
      pages: 1,
      built: false,
    },
    {
      id: 'header-global',
      base: 'header',
      desc: 'Block variant: header',
      pages: 1,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg',
      base: 'hero',
      desc: 'heading + 3 CTAs + image',
      pages: 2,
      built: false,
    },
    {
      id: '2 headings + 1 image + 3 ctas block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + 3 CTAs + image',
      pages: 2,
      built: false,
    },
    {
      id: 'breadcrumbs-minimal-dark',
      base: 'breadcrumbs',
      desc: 'list',
      pages: 44,
      built: true,
    },
    {
      id: 'carousel-minimal-dark-withimg',
      base: 'carousel',
      desc: '2 CTAs + image + list',
      pages: 14,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg',
      base: 'tabs',
      desc: 'heading + text + image + list',
      pages: 16,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-1',
      base: 'hero',
      desc: 'heading + text + image',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-1',
      base: 'tabs',
      desc: '32 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-2',
      base: 'hero',
      desc: 'image',
      pages: 14,
      built: false,
    },
    {
      id: 'accordion-minimal-dark',
      base: 'accordion',
      desc: 'heading + text + 7 CTAs',
      pages: 2,
      built: true,
    },
    {
      id: 'carousel-minimal-dark-withimg-1',
      base: 'carousel',
      desc: 'heading + text + 2 CTAs + 3 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-3',
      base: 'hero',
      desc: 'heading + image',
      pages: 11,
      built: false,
    },
    {
      id: '1 heading + 1 image + 1 paragraph block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + text + image',
      pages: 4,
      built: false,
    },
    {
      id: 'cards-minimal-dark-withimg',
      base: 'cards',
      desc: '4 images + list',
      pages: 2,
      built: false,
    },
    {
      id: '1 cta block-minimal-dark',
      base: 'unknown',
      desc: '1 CTAs',
      pages: 2,
      built: false,
    },
    {
      id: '1 heading + 4 images + 1 cta + 1 list block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + 1 CTAs + 4 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'quote-minimal-dark-withimg',
      base: 'quote',
      desc: 'heading + image',
      pages: 2,
      built: false,
    },
    {
      id: '1 heading + 1 image block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + image',
      pages: 9,
      built: false,
    },
    {
      id: '1 image block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'image',
      pages: 10,
      built: false,
    },
    {
      id: '1 heading + 1 image + 3 ctas + 1 paragraph block-minimal-dark',
      base: 'unknown',
      desc: 'heading + text + 3 CTAs + image',
      pages: 12,
      built: false,
    },
    {
      id: 'cards-minimal-dark-withimg-1',
      base: 'cards',
      desc: '5 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'carousel-minimal-dark-withimg-2',
      base: 'carousel',
      desc: '2 CTAs + 2 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-2',
      base: 'tabs',
      desc: 'heading + text + 2 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'carousel-minimal-dark-withimg-3',
      base: 'carousel',
      desc: '2 CTAs + 3 images + list',
      pages: 14,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-3',
      base: 'tabs',
      desc: 'heading + text + 5 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-4',
      base: 'tabs',
      desc: 'heading + text + 3 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-5',
      base: 'tabs',
      desc: 'heading + text + 6 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-6',
      base: 'tabs',
      desc: 'heading + text + 7 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-4',
      base: 'hero',
      desc: 'heading + 2 images + list',
      pages: 1,
      built: false,
    },
    {
      id: 'quote-minimal-dark-withimg-1',
      base: 'quote',
      desc: 'text + image',
      pages: 2,
      built: false,
    },
  ],
  groups: [
    {
      path: '/',
      pages: 11,
      confidence: '100%',
    },
    {
      path: '/ca/en',
      pages: 4,
      confidence: '90%',
    },
    {
      path: '/ca/en/adventures',
      pages: 16,
      confidence: '95%',
    },
    {
      path: '/ca/en/magazine',
      pages: 6,
      confidence: '95%',
    },
    {
      path: '/ca/en/magazine/members-only',
      pages: 2,
      confidence: '90%',
    },
    {
      path: '/us/en',
      pages: 4,
      confidence: '90%',
    },
    {
      path: '/us/en/adventures',
      pages: 16,
      confidence: '95%',
    },
    {
      path: '/us/en/magazine',
      pages: 5,
      confidence: '95%',
    },
  ],
  plan: [
    {
      phase: 'Step 1',
      title: 'Project Setup & Import Infrastructure',
      status: 'pending',
      effort: '2–3 days',
      desc: 'Scaffold the EDS project from the AEM boilerplate, wire up the content source, and build the reusable import pipeline (block parsers, site-wide cleanup transformer, import script) so every later step can pull content automatically.',
    },
    {
      phase: 'Step 2',
      title: 'Base & Global Styles (Design System)',
      status: 'pending',
      effort: '3–4 days',
      desc: 'Establish the foundation first: extract WKND brand tokens (Asar serif headings, Source Sans Pro body, yellow #ffeb00 accent, dark #202020), and set global styles.css — typography scale, colors, spacing, buttons, and section defaults. Everything built afterwards inherits this.',
    },
    {
      phase: 'Step 3',
      title: 'Header & Footer (Global Blocks)',
      status: 'pending',
      effort: '2–3 days',
      desc: 'Build the site-wide chrome next, since every page uses it: the WKND header (logo, main nav, locale switcher, search) and the localized footer (nav, social links, legal). Wired as nav/footer blocks loaded on every template.',
    },
    {
      phase: 'Step 4',
      title: 'Homepage Template',
      status: 'pending',
      effort: '3–4 days',
      desc: 'First content template (11 pages). Build & style its blocks — hero carousel, featured-article hero, and cards grids — then import and verify the homepage and its locale variants.',
    },
    {
      phase: 'Step 5',
      title: 'Adventure Detail & Adventures Listing',
      status: 'pending',
      effort: '4–5 days',
      desc: 'Largest template group (34 pages). Build breadcrumbs, carousel (reused), metadata sidebar, and tabs blocks; then the listing page (hero + filterable card grid). Import and verify all adventure pages.',
    },
    {
      phase: 'Step 6',
      title: 'Article & Content-Listing Templates',
      status: 'pending',
      effort: '3–4 days',
      desc: 'Magazine article (17 pages) — quote, share/related cards, breadcrumbs (reused) — and the about-us / magazine-landing profile-card grids. Import and verify.',
    },
    {
      phase: 'Step 7',
      title: 'FAQ Template',
      status: 'pending',
      effort: '1–2 days',
      desc: 'Smallest template (2 pages). Build the accordion block and contact sidebar, import and verify. Completes coverage of all 6 templates.',
    },
    {
      phase: 'Step 8',
      title: 'Full Locale Rollout',
      status: 'pending',
      effort: '3–4 days',
      desc: 'With every template proven, bulk-import the remaining pages across all 7 locales (us, ca, ch, de, fr, es, it), reconciling per-locale content, links, and language switcher targets.',
    },
    {
      phase: 'Step 9',
      title: 'Verification, QA & Launch',
      status: 'pending',
      effort: '3–5 days',
      desc: 'Full-site visual critique against the original, accessibility (WCAG 2.1 AA) and PageSpeed (target 100) checks, cross-locale QA, then production cutover.',
    },
  ],
  effortSummary: {
    totalLow: 24,
    totalHigh: 34,
    unit: 'developer-days',
    note: 'Sequential build order: foundation first (setup → global styles → header/footer), then one template at a time (blocks + import + verify), then the multi-locale rollout, then launch. Estimate assumes a single experienced EDS developer; template steps can be parallelized across developers to compress the calendar timeline.',
  },
};

export default reportData;
