// Auto-generated migration scope data (from catalog analysis).
const reportData = {
  meta: {
    source: 'https://wknd.site/us/en.html',
    date: '2026-07-22',
    method: 'crawl',
  },
  metrics: {
    totalPages: 64,
    totalTemplates: 6,
    analyzedTemplates: 6,
    totalBlockTypes: 31,
    edsBlockVariants: 24,
    unknownBlockVariants: 7,
    localeCount: 7,
    percentAnalyzed: 100,
    pagesAnalyzed: 64,
    pagesFailed: 0,
  },
  locales: [
    {
      locale: 'us',
      pages: 27,
    },
    {
      locale: 'ca',
      pages: 30,
    },
    {
      locale: 'ch',
      pages: 3,
    },
    {
      locale: 'de',
      pages: 1,
    },
    {
      locale: 'fr',
      pages: 1,
    },
    {
      locale: 'es',
      pages: 1,
    },
    {
      locale: 'it',
      pages: 1,
    },
  ],
  templates: [
    {
      name: 'adventure-detail',
      count: 32,
      desc: 'Adventure detail page: breadcrumb, full-width hero carousel, two-column layout with a metadata sidebar and tabbed rich-text content with inline image',
      rep: 'https://wknd.site/ca/en/adventures/bali-surf-camp.html',
      urls: [
        'https://wknd.site/ca/en/adventures/bali-surf-camp.html',
        'https://wknd.site/ca/en/adventures/beervana-portland.html',
        'https://wknd.site/ca/en/adventures/climbing-new-zealand.html',
        'https://wknd.site/ca/en/adventures/colorado-rock-climbing.html',
        'https://wknd.site/ca/en/adventures/cycling-southern-utah.html',
        'https://wknd.site/ca/en/adventures/cycling-tuscany.html',
        'https://wknd.site/ca/en/adventures/downhill-skiing-wyoming.html',
        'https://wknd.site/ca/en/adventures/gastronomic-marais-tour.html',
        'https://wknd.site/ca/en/adventures/napa-wine-tasting.html',
        'https://wknd.site/ca/en/adventures/riverside-camping-australia.html',
        'https://wknd.site/ca/en/adventures/ski-touring-mont-blanc.html',
        'https://wknd.site/ca/en/adventures/surf-camp-costa-rica.html',
        'https://wknd.site/ca/en/adventures/tahoe-skiing.html',
        'https://wknd.site/ca/en/adventures/west-coast-cycling.html',
        'https://wknd.site/ca/en/adventures/whistler-mountain-biking.html',
        'https://wknd.site/ca/en/adventures/yosemite-backpacking.html',
        'https://wknd.site/us/en/adventures/bali-surf-camp.html',
        'https://wknd.site/us/en/adventures/beervana-portland.html',
        'https://wknd.site/us/en/adventures/climbing-new-zealand.html',
        'https://wknd.site/us/en/adventures/colorado-rock-climbing.html',
        'https://wknd.site/us/en/adventures/cycling-southern-utah.html',
        'https://wknd.site/us/en/adventures/cycling-tuscany.html',
        'https://wknd.site/us/en/adventures/downhill-skiing-wyoming.html',
        'https://wknd.site/us/en/adventures/gastronomic-marais-tour.html',
        'https://wknd.site/us/en/adventures/napa-wine-tasting.html',
        'https://wknd.site/us/en/adventures/riverside-camping-australia.html',
        'https://wknd.site/us/en/adventures/ski-touring-mont-blanc.html',
        'https://wknd.site/us/en/adventures/surf-camp-costa-rica.html',
        'https://wknd.site/us/en/adventures/tahoe-skiing.html',
        'https://wknd.site/us/en/adventures/west-coast-cycling.html',
        'https://wknd.site/us/en/adventures/whistler-mountain-biking.html',
        'https://wknd.site/us/en/adventures/yosemite-backpacking.html',
      ],
      analyzed: true,
      blocks: [
        'breadcrumbs-minimal-dark',
        'carousel-minimal-dark',
        'metadata-minimal-dark',
        'tabs-minimal-dark',
      ],
    },
    {
      name: 'article',
      count: 12,
      desc: 'Magazine article page: full-width hero image, breadcrumb, article title and byline, rich-text body with section headings and inline images, a share sidebar with related-story links, and author footer',
      rep: 'https://wknd.site/ca/en/magazine/arctic-surfing.html',
      urls: [
        'https://wknd.site/ca/en/magazine/arctic-surfing.html',
        'https://wknd.site/ca/en/magazine/guide-la-skateparks.html',
        'https://wknd.site/ca/en/magazine/members-only/alaskan-adventure.html',
        'https://wknd.site/ca/en/magazine/members-only/fly-fishing-the-amazon.html',
        'https://wknd.site/ca/en/magazine/san-diego-surf.html',
        'https://wknd.site/ca/en/magazine/ski-touring.html',
        'https://wknd.site/ca/en/magazine/western-australia.html',
        'https://wknd.site/us/en/magazine/arctic-surfing.html',
        'https://wknd.site/us/en/magazine/guide-la-skateparks.html',
        'https://wknd.site/us/en/magazine/san-diego-surf.html',
        'https://wknd.site/us/en/magazine/ski-touring.html',
        'https://wknd.site/us/en/magazine/western-australia.html',
      ],
      analyzed: true,
      blocks: [
        'breadcrumbs-minimal-dark',
        'quote-minimal-dark',
        'cards-share-minimal-dark',
      ],
    },
    {
      name: 'homepage',
      count: 11,
      desc: 'Locale landing page: full-width hero carousel, featured article split layout, recent articles card row, secondary hero, and a destination card grid',
      rep: 'https://wknd.site/ca/en.html',
      urls: [
        'https://wknd.site/ca/en.html',
        'https://wknd.site/ca/fr.html',
        'https://wknd.site/ch/de.html',
        'https://wknd.site/ch/fr.html',
        'https://wknd.site/ch/it.html',
        'https://wknd.site/de/de.html',
        'https://wknd.site/es/es.html',
        'https://wknd.site/fr/fr.html',
        'https://wknd.site/it/it.html',
        'https://wknd.site/us/en.html',
        'https://wknd.site/us/es.html',
      ],
      analyzed: true,
      blocks: [
        'carousel-minimal-dark',
        'hero-minimal-dark',
        'cards-minimal-dark',
      ],
    },
    {
      name: 'content-listing',
      count: 5,
      desc: 'Editorial listing page with a section title, intro text, and repeated rows of circular/portrait cards with names and social links (about-us and magazine landing)',
      rep: 'https://wknd.site/ca/en/about-us.html',
      urls: [
        'https://wknd.site/ca/en/about-us.html',
        'https://wknd.site/ca/en/magazine.html',
        'https://wknd.site/ca/en/magazine/members-only.html',
        'https://wknd.site/us/en/about-us.html',
        'https://wknd.site/us/en/magazine.html',
      ],
      analyzed: true,
      blocks: [
        'cards-profile-minimal-dark',
      ],
    },
    {
      name: 'adventures-listing',
      count: 2,
      desc: 'Adventures listing page: full-width hero with overlay intro card and a filterable grid of adventure teaser cards',
      rep: 'https://wknd.site/ca/en/adventures.html',
      urls: [
        'https://wknd.site/ca/en/adventures.html',
        'https://wknd.site/us/en/adventures.html',
      ],
      analyzed: true,
      blocks: [
        'hero-minimal-dark',
        'tabs-minimal-dark',
        'cards-minimal-dark',
      ],
    },
    {
      name: 'faq',
      count: 2,
      desc: 'FAQ page: title, hero image, intro paragraph, accordion of question/answer items, and a right-hand contact sidebar',
      rep: 'https://wknd.site/ca/en/faqs.html',
      urls: [
        'https://wknd.site/ca/en/faqs.html',
        'https://wknd.site/us/en/faqs.html',
      ],
      analyzed: true,
      blocks: [
        'accordion-minimal-dark',
      ],
    },
  ],
  blocks: [
    {
      id: 'footer-global',
      base: 'footer',
      desc: 'Block variant: footer',
      pages: 1,
      built: false,
    },
    {
      id: 'header-global',
      base: 'header',
      desc: 'Block variant: header',
      pages: 1,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg',
      base: 'hero',
      desc: 'heading + 3 CTAs + image',
      pages: 2,
      built: false,
    },
    {
      id: '2 headings + 1 image + 3 ctas block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + 3 CTAs + image',
      pages: 2,
      built: false,
    },
    {
      id: 'breadcrumbs-minimal-dark',
      base: 'breadcrumbs',
      desc: 'list',
      pages: 44,
      built: true,
    },
    {
      id: 'carousel-minimal-dark-withimg',
      base: 'carousel',
      desc: '2 CTAs + image + list',
      pages: 14,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg',
      base: 'tabs',
      desc: 'heading + text + image + list',
      pages: 16,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-1',
      base: 'hero',
      desc: 'heading + text + image',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-1',
      base: 'tabs',
      desc: '32 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-2',
      base: 'hero',
      desc: 'image',
      pages: 14,
      built: false,
    },
    {
      id: 'accordion-minimal-dark',
      base: 'accordion',
      desc: 'heading + text + 7 CTAs',
      pages: 2,
      built: true,
    },
    {
      id: 'carousel-minimal-dark-withimg-1',
      base: 'carousel',
      desc: 'heading + text + 2 CTAs + 3 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-3',
      base: 'hero',
      desc: 'heading + image',
      pages: 11,
      built: false,
    },
    {
      id: '1 heading + 1 image + 1 paragraph block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + text + image',
      pages: 4,
      built: false,
    },
    {
      id: 'cards-minimal-dark-withimg',
      base: 'cards',
      desc: '4 images + list',
      pages: 2,
      built: false,
    },
    {
      id: '1 cta block-minimal-dark',
      base: 'unknown',
      desc: '1 CTAs',
      pages: 2,
      built: false,
    },
    {
      id: '1 heading + 4 images + 1 cta + 1 list block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + 1 CTAs + 4 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'quote-minimal-dark-withimg',
      base: 'quote',
      desc: 'heading + image',
      pages: 2,
      built: false,
    },
    {
      id: '1 heading + 1 image block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'heading + image',
      pages: 9,
      built: false,
    },
    {
      id: '1 image block-minimal-dark-withimg',
      base: 'unknown',
      desc: 'image',
      pages: 10,
      built: false,
    },
    {
      id: '1 heading + 1 image + 3 ctas + 1 paragraph block-minimal-dark',
      base: 'unknown',
      desc: 'heading + text + 3 CTAs + image',
      pages: 12,
      built: false,
    },
    {
      id: 'cards-minimal-dark-withimg-1',
      base: 'cards',
      desc: '5 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'carousel-minimal-dark-withimg-2',
      base: 'carousel',
      desc: '2 CTAs + 2 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-2',
      base: 'tabs',
      desc: 'heading + text + 2 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'carousel-minimal-dark-withimg-3',
      base: 'carousel',
      desc: '2 CTAs + 3 images + list',
      pages: 14,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-3',
      base: 'tabs',
      desc: 'heading + text + 5 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-4',
      base: 'tabs',
      desc: 'heading + text + 3 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-5',
      base: 'tabs',
      desc: 'heading + text + 6 images + list',
      pages: 2,
      built: false,
    },
    {
      id: 'tabs-minimal-dark-withimg-6',
      base: 'tabs',
      desc: 'heading + text + 7 images + list',
      pages: 4,
      built: false,
    },
    {
      id: 'hero-minimal-dark-withimg-4',
      base: 'hero',
      desc: 'heading + 2 images + list',
      pages: 1,
      built: false,
    },
    {
      id: 'quote-minimal-dark-withimg-1',
      base: 'quote',
      desc: 'text + image',
      pages: 2,
      built: false,
    },
  ],
  groups: [
    {
      path: '/',
      pages: 11,
      confidence: '100%',
    },
    {
      path: '/ca/en',
      pages: 4,
      confidence: '90%',
    },
    {
      path: '/ca/en/adventures',
      pages: 16,
      confidence: '95%',
    },
    {
      path: '/ca/en/magazine',
      pages: 6,
      confidence: '95%',
    },
    {
      path: '/ca/en/magazine/members-only',
      pages: 2,
      confidence: '90%',
    },
    {
      path: '/us/en',
      pages: 4,
      confidence: '90%',
    },
    {
      path: '/us/en/adventures',
      pages: 16,
      confidence: '95%',
    },
    {
      path: '/us/en/magazine',
      pages: 5,
      confidence: '95%',
    },
  ],
  plan: [
    [
      'Site scope & template discovery',
      'done',
      '64 pages crawled, grouped into 6 templates, 31 block variants cataloged.',
    ],
    [
      'Page analysis',
      'done',
      'All 6 representative pages analyzed — content structure, sections, and authoring decisions captured.',
    ],
    [
      'Block variants',
      'done',
      '10 EDS block variants created/reused (hero, carousel, cards, tabs, accordion, quote, breadcrumbs, metadata, profile & share cards).',
    ],
    [
      'Import infrastructure',
      'done',
      '10 parsers + site-wide cleanup transformer + reusable import script (import-wknd.js).',
    ],
    [
      'Content import',
      'done',
      '6 us/en representative pages imported.',
    ],
    [
      'Design migration',
      'done',
      'WKND brand tokens (Asar serif, Source Sans Pro, yellow #ffeb00 accent, dark footer) applied to global styles + all 10 blocks.',
    ],
    [
      'Navigation & footer',
      'next',
      'Instrument the WKND header (logo, main nav, locale switcher, search) and localized footer.',
    ],
    [
      'Verification',
      'next',
      'Preview locally and run visual critique against the original.',
    ],
  ],
};

export default reportData;
